### ISSUE TITLE
[FR] 可以增加触摸或者鼠标操作支持吗，在电脑或者平板上使用，非常漂亮的版本

### ISSUE THREAD

**Issue by molun** [lizongying/screening-room#5]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

可以增加触摸或者鼠标操作支持吗，在电脑或者平板上使用，非常漂亮的版本

**Comment by lizongying** [comment]
會增加，前期先支持電視
但現在還有很多bug待修復，功能也待完善
